params:
  docs:
    hide_folders:
    - crds
    - design
    external_docs:
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: latest
      branch: v0.49.1
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.49.1
      branch: v0.49.1
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.49.0
      branch: v0.49.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.48.1
      branch: v0.48.1
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: main
      branch: main
      dir: docs
