params:
  docs:
    hide_folders:
    - crds
    - design
    external_docs:
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: latest
      branch: v0.46.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.46.0
      branch: v0.46.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.45.0
      branch: v0.45.0
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: v0.44.1
      branch: v0.44.1
      dir: docs
    - repo: https://github.com/inspektor-gadget/inspektor-gadget.git
      name: main
      branch: main
      dir: docs
